cache:
  directories:
    - $HOME/.composer/cache

language: php

env:
  global:
    - COVERAGE=0 XDEBUG=0

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - hhvm-3.18

matrix:
  include:
    - php: hhvm-3.18
      sudo: required
      dist: trusty
      env: LARAVEL='5.4.*' XDEBUG=1
    - php: 5.5.9
      env: LARAVEL='5.2.*'
    - php: 5.5
      env: LARAVEL='5.2.*'
    - php: 5.6
      env: LARAVEL='5.2.*'
    - php: 5.6
      env: LARAVEL='5.3.*'
    - php: 5.6
      env: LARAVEL='5.4.*'
    - php: 7.0
      env: LARAVEL='5.2.*'
    - php: 7.0
      env: LARAVEL='5.3.*'
    - php: 7.0
      env: LARAVEL='5.4.*'
    - php: 7.0
      env: LARAVEL='5.5.*'
    - php: 7.1
      env: LARAVEL='5.2.*'
    - php: 7.1
      env: LARAVEL='5.3.*'
    - php: 7.1
      env: LARAVEL='5.4.*'
    - php: 7.1
      env: LARAVEL='5.5.*'
    - php: 7.2
      env: LARAVEL='5.2.*' XDEBUG=1
    - php: 7.2
      env: LARAVEL='5.3.*' XDEBUG=1
    - php: 7.2
      env: LARAVEL='5.4.*' XDEBUG=1
    - php: 7.2
      env: COVERAGE=1 LARAVEL='5.5.*' XDEBUG=1
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose
